// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using OrbitAgro.API.Data;

#nullable disable

namespace OrbitAgro.API.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260609211953_AdicionarFonteSateliteLogErro")]
    partial class AdicionarFonteSateliteLogErro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrbitAgro.API.Models.AlertaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaCultivoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DataAlerta")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("StatusAlerta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("AreaCultivoId");

                    b.ToTable("TB_ALERTA");
                });

            modelBuilder.Entity("OrbitAgro.API.Models.AreaCultivoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cultura")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<double>("Hectares")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("Latitude")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("Longitude")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("NomeArea")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<int>("ProdutorId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutorId");

                    b.ToTable("TB_AREA_CULTIVO");
                });

            modelBuilder.Entity("OrbitAgro.API.Models.MonitoramentoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaCultivoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DataLeitura")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<double>("IndiceNdvi")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("NdviAnterior")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("TemperaturaSolo")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("UmidadeSolo")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("Id");

                    b.HasIndex("AreaCultivoId");

                    b.ToTable("TB_MONITORAMENTO");
                });

            modelBuilder.Entity("OrbitAgro.API.Models.ProdutorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.HasKey("Id");

                    b.ToTable("TB_PRODUTOR");
                });

            modelBuilder.Entity("OrbitAgro.API.Models.AlertaEntity", b =>
                {
                    b.HasOne("OrbitAgro.API.Models.AreaCultivoEntity", "AreaCultivo")
                        .WithMany("Alertas")
                        .HasForeignKey("AreaCultivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaCultivo");
                });

            modelBuilder.Entity("OrbitAgro.API.Models.AreaCultivoEntity", b =>
                {
                    b.HasOne("OrbitAgro.API.Models.ProdutorEntity", "Produtor")
                        .WithMany("Areas")
                        .HasForeignKey("ProdutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produtor");
                });

            modelBuilder.Entity("OrbitAgro.API.Models.MonitoramentoEntity", b =>
                {
                    b.HasOne("OrbitAgro.API.Models.AreaCultivoEntity", "AreaCultivo")
                        .WithMany("Monitoramentos")
                        .HasForeignKey("AreaCultivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaCultivo");
                });

            modelBuilder.Entity("OrbitAgro.API.Models.AreaCultivoEntity", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Monitoramentos");
                });

            modelBuilder.Entity("OrbitAgro.API.Models.ProdutorEntity", b =>
                {
                    b.Navigation("Areas");
                });
#pragma warning restore 612, 618
        }
    }
}
